hide:
  - toc
site_name: Bilheteria Digital
nav:
  - Home: index.md
  - Atas:
      - Ata 1: atas/IHC_Ata_01.md
      - Ata 2: atas/IHC_Ata_02.md
      - Ata 3: atas/IHC_Ata_03.md
  - Planejamento:
      - Ferramentas: planejamento/ferramentas.md
      - Cronograma: planejamento/cronograma.md
theme:
  hide:
    - navigation
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.footer
  name: material
  palette:
    primary: "red"
    accent: "black"
    background: "white"
    text: "black"
    code:
      bg: "black"
      fg: "white"
  language: pt-BR
  favicon: assets/bilheteria.png
  logo: assets/bilheteria.png

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
