repo_url: https://github.com/Interacao-Humano-Computador/2023.1-BilheteriaDigital
repo_name: 2023.1-BilheteriaDigital

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - glightbox

site_name: Bilheteria Digital
nav:
  - Home: index.md
  - Apresentações:
      - Apresentação 1: apresentacao/apresentacao1.md
      - Apresentação 2: apresentacao/apresentacao2.md
      - Apresentação 3: apresentacao/apresentacao3.md
      - Apresentação 4: apresentacao/apresentacao4.md
      - Apresentação 5: apresentacao/apresentacao5.md
      - Apresentação 6: apresentacao/apresentacao6.md
      - Apresentação 7: apresentacao/apresentacao7.md
      - Apresentação 8: apresentacao/apresentacao8.md
      - Apresentação 9: apresentacao/apresentacao9.md
  - Atas:
      - Ata 1: atas/IHC_Ata_01.md
      - Ata 2: atas/IHC_Ata_02.md
      - Ata 3: atas/IHC_Ata_03.md
      - Ata 4: atas/IHC_Ata_04.md
      - Ata 5: atas/IHC_Ata_05.md
      - Ata 6: atas/IHC_Ata_06.md
      - Ata 7: atas/IHC_Ata_07.md
      - Ata 8: atas/IHC_Ata_08.md
      - Ata 9: atas/IHC_Ata_09.md
      - Ata 10: atas/IHC_Ata_10.md
      - Ata 11: atas/IHC_Ata_11.md
      - Ata 12: atas/IHC_Ata_12.md
      - Ata 13: atas/IHC_Ata_13.md
  - Planejamento:
      - Cronograma: planejamento/cronograma.md
      - Ferramentas: planejamento/ferramentas.md
      - Metodologia: planejamento/metodologia.md
      - Sites avaliados: planejamento/sites-avaliados.md
      - Site escolhido: planejamento/site-escolhido.md
      - Processo design: planejamento/processo-design.md
  - Análise de Requisitos:
      - Aspectos Éticos: analise-de-requisitos/aspectos-eticos.md
      - Perfil de Usuário: analise-de-requisitos/perfil-usuario.md
      - Cenários: analise-de-requisitos/cenarios.md
      - Personas: analise-de-requisitos/personas.md
      - Análise de tarefas:
          - Análise Hierárquica de Tarefas: analise-de-requisitos/analise-de-tarefas/hta.md
          - GOMS: analise-de-requisitos/analise-de-tarefas/goms.md
      - Metas de Usabilidade: analise-de-requisitos/metas-usabilidade.md
      - Princípios Gerais: analise-de-requisitos/principios.md
      - Guia de Estilo: analise-de-requisitos/guia-de-estilo.md
      - Características Gerais: analise-de-requisitos/caracteristicas.md
  - Design, Avaliação e Desenvolvimento:
      - Nível 1:
          - Análise de Tarefas:
              - Planejamento da Avaliação da Análise de Tarefas: design-avaliacao-desenvolvimento/nivel-1/analise-de-tarefas-dad/planejamento-avaliavao-at.md
              - Planejamento do Relato dos Resultados da Avaliação: design-avaliacao-desenvolvimento/nivel-1/analise-de-tarefas-dad/planejamento-relato-resultados-at.md
              - Relato do Resultado: design-avaliacao-desenvolvimento/nivel-1/analise-de-tarefas-dad/resultado-relato-analise-de-tarefas.md
          - Storyboard:
              - Planejamento da Avaliação do Storyboard: design-avaliacao-desenvolvimento/nivel-1/storyboard-dad/planejamento-avaliavao-sb.md
              - Planejamento do Relato dos Resultados: design-avaliacao-desenvolvimento/nivel-1/storyboard-dad/planejamento-relato-resultados-sb.md
              - Relato do Resultado: design-avaliacao-desenvolvimento/nivel-1/storyboard-dad/relato-resultado-storyboard.md
              - Storyboards: design-avaliacao-desenvolvimento/nivel-1/storyboard-dad/storyboard.md
      - Nível 2:
          - Protótipo de Papel:
              - Planejamento da Avaliação do Protótipo de Papel: design-avaliacao-desenvolvimento/nivel-2/prototipo-papel-dad/planejamento-avaliacao-pp.md
              - Planejamento do Relato dos Resultados: design-avaliacao-desenvolvimento/nivel-2/prototipo-papel-dad/planejamento-relato-resultados-pp.md
              - Relato dos Resultados do Protótipo de Papel: design-avaliacao-desenvolvimento/nivel-2/prototipo-papel-dad/relato-dos-resultados-pp.md
      - Nível 3:
          - Protótipo de Alta Fidelidade:
              - Planejamento da Avaliação do Protótipo de Alta Fidelidade: design-avaliacao-desenvolvimento/nivel-3/planejamento-avaliacao-paf.md
              - Planejamento do Relato dos Resultados: design-avaliacao-desenvolvimento/nivel-3/planejamento-relato-paf.md
              - Relato dos Resultados do Protótipo de Alta Fidelidade: design-avaliacao-desenvolvimento/nivel-3/relato-resultados-paf.md
  - Verificação:
      - Verificação do Grupo:
          - Etapa 1:
              - Planejamento da Verificação da Etapa 1: verificacao/grupo/etapa1/planejamento-verificacao-etapa1-grupo.md
              - Cronograma: verificacao/grupo/etapa1/verificacao-cronogrma.md
              - Ferramentas: verificacao/grupo/etapa1/verificacao-ferramentas.md
              - Processo de Design: verificacao/grupo/etapa1/verificacao-processo-design.md
              - Site Escolhido: verificacao/grupo/etapa1/verificacao-site-escolhido.md
          - Etapa 2:
              - Planejamento da Verificação da Etapa 2: verificacao/grupo/etapa2/planejamento-verificacao-etapa2-grupo.md
              - Personas: verificacao/grupo/etapa2/personas.md
              - Aspectos éticos: verificacao/grupo/etapa2/aspectos-eticos.md
              - Cenários: verificacao/grupo/etapa2/cenarios.md
              - Perfil de Usuário: verificacao/grupo/etapa2/perfil-de-usuario.md
              - Análise de Tarefas - Análise Hierárquica de Tarefas: verificacao/grupo/etapa2/at-hta.md
              - Análise de Tarefas - GOMS: verificacao/grupo/etapa2/at-goms.md
          - Etapa 3:
              - Planejamento da Verificação da Etapa 3: verificacao/grupo/etapa3/planejamento-verificacao-etapa3-grupo.md
              - Guia de Estilo: verificacao/grupo/etapa3/guia-de-estilo.md
              - Características Gerais: verificacao/grupo/etapa3/caracteristicas-gerais.md
              - Princípios Gerais: verificacao/grupo/etapa3/principios-gerais.md
              - Metas de Usabilidade: verificacao/grupo/etapa3/metas-usabilidade.md
          - Etapa 4:
              - Planejamento da Verificação da Etapa 4: verificacao/grupo/etapa4/planejamento-verificacao-etapa4-grupo.md
              - Planejamento da Avaliação da Análise de Tarefas: verificacao/grupo/etapa4/verificacao-planejamento-analise.md
              - Planejamento da Avaliação do Storyboard: verificacao/grupo/etapa4/verificacao-planejamento-storyboard.md
              - Planejamento do Relato dos Resultados da Avaliação da Análise de Tarefas: verificacao/grupo/etapa4/verificacao-planejamento-relato-analise.md
              - Planejamento do Relato dos Resultados da Avaliação do Storyboard: verificacao/grupo/etapa4/verificacao-planejamento-relato-sb.md
              - Storyboards: verificacao/grupo/etapa4/verificacao-storyboard.md
          - Etapa 5:
              - Planejamento da Verificação da Etapa 5: verificacao/grupo/etapa5/planejamento-verificacao-etapa5-grupo.md
              - Planejamento da Avaliação do Protótipo de Papel: verificacao/grupo/etapa5/verificacao-planejamento-prototipo.md
              - Planejamento do Relato dos Resultados do Protótipo de Papel: verificacao/grupo/etapa5/verificacao-planejamento-relato-resultado-pp.md
              - Relato dos Resultados da Análise de Tarefas: verificacao/grupo/etapa5/verificacao-relato-resultados-at.md
              - Relato dos Resultados do Storyboard: verificacao/grupo/etapa5/verificacao-relato-resultados-sb.md
              - Protótipo de Papel: verificacao/grupo/etapa5/prototipo-de-papel.md
          - Etapa 7:
              - Planejamento da Verificação da Etapa 7: verificacao/grupo/etapa7/planejamento-verificacao-etapa7-grupo.md
              - Planejamento da Avaliação do Protótipo de Alta Fidelidade: verificacao/grupo/etapa7/verificacao-planejamento-alta.md
              - Planejamento do Relato dos Resultados de Alta Fidelidade: verificacao/grupo/etapa7/verificacao-planejamento-relato-resultado-alta.md
              - Relato dos Resultados do Protótipo de Papel: verificacao/grupo/etapa7/verificacao-relato-resultados-pp.md
      - Verificação do Grupo 2:
          - Etapa 1:
              - Planejamento da Verificação: verificacao/grupo2/etapa1/planejamento.md
              - Cronograma: verificacao/grupo2/etapa1/cronograma.md
              - Ferramentas: verificacao/grupo2/etapa1/ferramenta.md
              - Processo de Design: verificacao/grupo2/etapa1/processo-design.md
              - Site escolhido: verificacao/grupo2/etapa1/site-escolhido.md
          - Etapa 2:
              - Planejamento da Verificação: verificacao/grupo2/etapa2/planejamento-verificacao-etapa2-grupo2.md
              - Análise de Tarefas: verificacao/grupo2/etapa2/analise-de-tarefas.md
              - Perfil de Usuário: verificacao/grupo2/etapa2/perfil-de-usuario.md
              - Personas: verificacao/grupo2/etapa2/personas.md
              - Pesquisa sobre Ética: verificacao/grupo2/etapa2/pesquisa-sobre-etica.md
          - Etapa 3:
              - Planejamento da Verificação: verificacao/grupo2/etapa3/planejamento-verificacao-etapa3-grupo2.md
              - Guia de Estilo: verificacao/grupo2/etapa3/guia-de-estilo.md
              - Metas de Usabilidade: verificacao/grupo2/etapa3/metas-de-usabilidade.md
              - Princípios Gerais: verificacao/grupo2/etapa3/principios-gerais.md
              - Características Gerais: verificacao/grupo2/etapa3/caracteristicas-gerais.md
          - Etapa 4:
              - Planejamento da Avaliação da Análise de Tarefas: verificacao/grupo2/etapa4/planejamento-aval-analise.md
              - Planejamento do Relato dos Resultados da Avaliação: verificacao/grupo2/etapa4/planejamento-relato-analise.md
              - Planejamento da Avaliação do Storyboard: verificacao/grupo2/etapa4/planejamento-aval-sb.md
              - Planejamento do Relato dos Resultados do Storyboard: verificacao/grupo2/etapa4/planejamento-relato-sb.md
          - Etapa 5:
              - Planejamento da Verificação: verificacao/grupo2/etapa5/planejamento-verificacao-etapa5-grupo2.md
              - Relato dos Resultados do Storyboard: verificacao/grupo2/etapa5/relato-sb.md
              - Relato dos Resultados da Análise de Tarefas: verificacao/grupo2/etapa5/relato-analise.md
              - Planejamento da Avaliação do Protótipo de Papel: verificacao/grupo2/etapa5/planejamento-aval-papel.md
              - Planejamento do Relato dos Resultados do Protótipo de Papel: verificacao/grupo2/etapa5/planejamento-relato-papel.md
  - Entrega Final:
      - Site Selecionado: entrega-final/site-selecionado.md
      - Ciclo de Vida Utilizado: entrega-final/ciclo-de-vida.md
      - Planejamento dos Recursos e das Entregas (Cronograma): entrega-final/cronograma-projeto.md
      - Execução do Projeto: entrega-final/execucao-projeto.md
      - Resultados Alcançados com a Execução do Projeto: entrega-final/resultados-execucao.md
      - Ferramentas Utilizadas: entrega-final/ferramentas-utilizadas.md
      - Técnicas Utilizadas: entrega-final/tecnicas-utilizadas.md
      - Artefatos Criados: entrega-final/artefatos-criados.md
      - Síntese das Avaliações: entrega-final/sintese-avaliacao.md
      - Síntese das Verificações: entrega-final/sintese-verificacoes.md
      - Síntese das Apresentações: entrega-final/sintese-apresentacao.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/circle-half-full
        name: Mudar para o modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/circle-half-full
        name: Mudar para o modo claro

  language: pt-BR
  favicon: assets/bilheteria.png
  logo: assets/bilheteria.png

extra:
  version:
    provider: mike

extra_css: [stylesheets/extra.css]
