repo_url: https://github.com/Interacao-Humano-Computador/2023.1-BilheteriaDigital
repo_name: 2023.1-BilheteriaDigital
site_name: Bilheteria Digital

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Apresentação: apresentacao.md
  - Atas:
      - Ata 1: atas/IHC_Ata_01.md
      - Ata 2: atas/IHC_Ata_02.md
      - Ata 3: atas/IHC_Ata_03.md
      - Ata 4: atas/IHC_Ata_04.md
      - Ata 5: atas/IHC_Ata_05.md
      - Ata 6: atas/IHC_Ata_06.md
  - Planejamento:
      - Cronograma: planejamento/cronograma.md
      - Ferramentas: planejamento/ferramentas.md
      - Metodologia: planejamento/metodologia.md
      - Sites avaliados: planejamento/sites-avaliados.md
      - Site escolhido: planejamento/site-escolhido.md
      - Processo design: planejamento/processo-design.md
theme:
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/circle-half-full
        name: Claro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/circle-half-full
        name: Escuro

  language: pt-BR
  favicon: assets/bilheteria.png
  logo: assets/bilheteria.png

extra_css: [stylesheets/extra.css]
