repo_url: https://github.com/Interacao-Humano-Computador/2023.1-BilheteriaDigital
repo_name: 2023.1-BilheteriaDigital
hide:
  - toc
site_name: Bilheteria Digital
nav:
  - Home: index.md
  - Atas:
      - Ata 1: atas/IHC_Ata_01.md
      - Ata 2: atas/IHC_Ata_02.md
      - Ata 3: atas/IHC_Ata_03.md
      - Ata 4: atas/IHC_Ata_04.md
  - Planejamento:
      - Ferramentas: planejamento/ferramentas.md
      - Cronograma: planejamento/cronograma.md
      - Metodologia: metodologia.md
theme:
  hide:
    - navigation
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.footer
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/circle-half-full
        name: Claro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/circle-half-full
        name: Escuro

  language: pt-BR
  favicon: assets/bilheteria.png
  logo: assets/bilheteria.png

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css: [stylesheets/extra.css]