repo_url: https://github.com/Interacao-Humano-Computador/2023.1-BilheteriaDigital
repo_name: 2023.1-BilheteriaDigital

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - glightbox

site_name: Bilheteria Digital
nav:
  - Home: index.md
  - Apresentações:
      - Apresentação 1: apresentacao/apresentacao1.md
      - Apresentação 2: apresentacao/apresentacao2.md
      - Apresentação 3: apresentacao/apresentacao3.md
      - Apresentação 4: apresentacao/apresentacao4.md
      - Apresentação 5: apresentacao/apresentacao5.md
  - Atas:
      - Ata 1: atas/IHC_Ata_01.md
      - Ata 2: atas/IHC_Ata_02.md
      - Ata 3: atas/IHC_Ata_03.md
      - Ata 4: atas/IHC_Ata_04.md
      - Ata 5: atas/IHC_Ata_05.md
      - Ata 6: atas/IHC_Ata_06.md
      - Ata 7: atas/IHC_Ata_07.md
      - Ata 8: atas/IHC_Ata_08.md
      - Ata 9: atas/IHC_Ata_09.md
  - Planejamento:
      - Cronograma: planejamento/cronograma.md
      - Ferramentas: planejamento/ferramentas.md
      - Metodologia: planejamento/metodologia.md
      - Sites avaliados: planejamento/sites-avaliados.md
      - Site escolhido: planejamento/site-escolhido.md
      - Processo design: planejamento/processo-design.md
  - Análise de Requisitos:
      - Aspectos Éticos: analise-de-requisitos/aspectos-eticos.md
      - Perfil de Usuário: analise-de-requisitos/perfil-usuario.md
      - Cenários: analise-de-requisitos/cenarios.md
      - Personas: analise-de-requisitos/personas.md
      - Análise de tarefas:
          - Análise Hierárquica de Tarefas: analise-de-requisitos/analise-de-tarefas/hta.md
          - GOMS: analise-de-requisitos/analise-de-tarefas/goms.md
      - Metas de Usabilidade: analise-de-requisitos/metas-usabilidade.md
      - Princípios Gerais: analise-de-requisitos/principios.md
      - Guia de Estilo: analise-de-requisitos/guia-de-estilo.md
      - Características Gerais: analise-de-requisitos/caracteristicas.md
  - Design, Avaliação e Desenvolvimento:
      - Nível 1:
          - Análise de Tarefas:
              - Planejamento da Avaliação da Análise de Tarefas: design-avaliacao-desenvolvimento/nivel-1/analise-de-tarefas-dad/planejamento-avaliavao-at.md
              - Planejamento do Relato dos Resultados da Avaliação: design-avaliacao-desenvolvimento/nivel-1/analise-de-tarefas-dad/planejamento-relato-resultados-at.md
              - Relato do Resultado: design-avaliacao-desenvolvimento/nivel-1/analise-de-tarefas-dad/resultado-relato-analise-de-tarefas.md
          - Storyboard:
              - Planejamento da Avaliação do Storyboard: design-avaliacao-desenvolvimento/nivel-1/storyboard-dad/planejamento-avaliavao-sb.md
              - Planejamento do Relato dos Resultados: design-avaliacao-desenvolvimento/nivel-1/storyboard-dad/planejamento-relato-resultados-sb.md
              - Relato do Resultado: design-avaliacao-desenvolvimento/nivel-1/storyboard-dad/relato-resultado-storyboard.md
              - Storyboards: design-avaliacao-desenvolvimento/nivel-1/storyboard-dad/storyboard.md
      - Nível 2:
          - Protótipo de Papel:
              - Planejamento da Avaliação do Protótipo de Papel: design-avaliacao-desenvolvimento/nivel-2/prototipo-papel-dad/planejamento-avaliacao-pp.md
              - Planejamento do Relato dos Resultados: design-avaliacao-desenvolvimento/nivel-2/prototipo-papel-dad/planejamento-relato-resultados-pp.md
  - Verificação Grupo 2:
      - Etapa 1:
          - Cronograma: verificacao/etapa1/cronograma.md
          - Ferramentas: verificacao/etapa1/ferramenta.md
          - Metodologia: verificacao/etapa1/metodologia.md
          - Processo de Design: verificacao/etapa1/processo-design.md
          - Site escolhido: verificacao/etapa1/site-escolhido.md
      - Etapa 2:
          - Análise de Tarefas: verificacao/etapa2/analise-de-tarefas.md
          - Perfil de Usuário: verificacao/etapa2/perfil-de-usuario.md
          - Personas: verificacao/etapa2/personas.md
          - Pesquisa sobre Ética: verificacao/etapa2/pesquisa-sobre-etica.md
      - Etapa 3:
          - Guia de Estilo: verificacao/etapa3/guia-de-estilo.md
          - Metas de Usabilidade: verificacao/etapa3/metas-de-usabilidade.md
          - Princípios Gerais: verificacao/etapa3/principios-gerais.md
          - Características Gerais: verificacao/etapa3/caracteristicas-gerais.md
      - Etapa 4:
          - Planejamento da Avaliação da Análise de Tarefas: verificacao/etapa4/planejamento-aval-analise.md
          - Planejamento do Relato dos Resultados da Avaliação: verificacao/etapa4/planejamento-relato-analise.md
          - Planejamento da Avaliação do Storyboard: verificacao/etapa4/planejamento-aval-sb.md
          - Planejamento do Relato dos Resultados do Storyboard: verificacao/etapa4/planejamento-relato-sb.md
      - Etapa 5:
          - Planejamento da Avaliação do Protótipo de Papel: verificacao/etapa5/planejamento-aval-papel.md
          - Planejamento do Relato dos Resultados do Protótipo de Papel: verificacao/etapa5/planejamento-relato-papel.md
          - Relato dos Resultados da Análise de Tarefas: verificacao/etapa5/relato-analise.md
          - Relato dos Resultados do Storyboard: verificacao/etapa5/relato-sb.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/circle-half-full
        name: Escuro

    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/circle-half-full
        name: Claro

  language: pt-BR
  favicon: assets/bilheteria.png
  logo: assets/bilheteria.png

extra:
  version:
    provider: mike

extra_css: [stylesheets/extra.css]
