repo_url: https://github.com/Interacao-Humano-Computador/2023.1-BilheteriaDigital
repo_name: 2023.1-BilheteriaDigital

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

site_name: Bilheteria Digital
nav:
  - Home: index.md
  - Apresentações:
      - Apresentação 1: apresentacao/apresentacao1.md
      - Apresentação 2: apresentacao/apresentacao2.md
  - Atas:
      - Ata 1: atas/IHC_Ata_01.md
      - Ata 2: atas/IHC_Ata_02.md
      - Ata 3: atas/IHC_Ata_03.md
      - Ata 4: atas/IHC_Ata_04.md
      - Ata 5: atas/IHC_Ata_05.md
      - Ata 6: atas/IHC_Ata_06.md
  - Planejamento:
      - Cronograma: planejamento/cronograma.md
      - Ferramentas: planejamento/ferramentas.md
      - Metodologia: planejamento/metodologia.md
      - Sites avaliados: planejamento/sites-avaliados.md
      - Site escolhido: planejamento/site-escolhido.md
      - Processo design: planejamento/processo-design.md
  - Análise de Requisitos:
      - Aspectos Éticos: analise-de-requisitos/aspectos-eticos.md
      - Perfil de Usuário: analise-de-requisitos/perfil-usuario.md
      - Cenários: analise-de-requisitos/cenarios.md
      - Personas: analise-de-requisitos/personas.md
      - Análise de tarefas:
          - Análise Hierárquica de Tarefas: analise-de-requisitos/analise-de-tarefas/hta.md
          - GOMS: analise-de-requisitos/analise-de-tarefas/goms.md
      - Princípios Gerais: analise-de-requisitos/principios.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/circle-half-full
        name: Escuro

    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/circle-half-full
        name: Claro

  language: pt-BR
  favicon: assets/bilheteria.png
  logo: assets/bilheteria.png

extra:
  version:
    provider: mike

extra_css: [stylesheets/extra.css]
