site_name: Bilheteria Digital
nav:
  - Home: index.md
  - Planejamento:
    - Ferramentas: ferramentas.md
    - Cronograma: cronograma.md
    - Metodologia: metodologia.md
  - Atas:
    - Ata 1: IHC_Ata_01.md
    - Ata 2: IHC_Ata_02.md
    - Ata 3: IHC_Ata_03.md

theme:
    name: material
    palette:
        primary: 'red'
        accent: 'black'
        background: 'white'
        text: 'black'
        code:
            bg: 'black'
            fg: 'white'
    language: pt-BR
    favicon: assets/bilheteria.png
    logo: assets/bilheteria.png
